### ISSUE TITLE
Error during npm run start: Missing .clasp.json and TypeError in UiDeploymentHandler

### ISSUE THREAD

**Issue by kng246** [google-marketing-solutions/vigenair#1]
While running the npm run start command in my project, I encountered an error related to a missing .clasp.json file and a TypeError in the UiDeploymentHandler. 

Additionally, the generated .clasp.json files seem to be empty ({})

The error output is as follows:

`Output location: /home/kiran/test/Pencil/ViGenAir/vigenair/ui/src/ui/dist/ui

Application bundle generation complete. [6.391 seconds]

> vigenair-aside@0.0.1 deploy-ui
> node deploy-ui.mjs

No valid /home/kiran/test/Pencil/ViGenAir/vigenair/ui/.clasp.json project file. You may need to `create` or `clone` a project first.
/home/kiran/test/Pencil/ViGenAir/vigenair/dist/common.js:144
        let webAppLink = lastNonEmptyLine.match(/- (.*) @.*/);
                                          ^

TypeError: Cannot read properties of undefined (reading 'match')
    at UiDeploymentHandler.deployUi (/home/kiran/test/Pencil/ViGenAir/vigenair/dist/common.js:144:43)
    at /home/kiran/test/Pencil/ViGenAir/vigenair/dist/index.js:87:41
    at Generator.next (<anonymous>)
    at fulfilled (/home/kiran/test/Pencil/ViGenAir/vigenair/dist/index.js:20:58)

Node.js v18.20.3
`

**Steps to Reproduce**

1. Clone the repository.
2. Navigate to the project directory.
3. Run the command npm run start.

Environment
   Node.js version: v18.20.3
   python version: 3.10.14

**Comment by kng246** [comment]
Noticed that a Cloud Run service named **vigenair** has been created in GCP. However, when trying to access the URL shown, it throws a 405 error.
Additionally, guidance is needed on how to properly access the webapp.

![image](https://github.com/google-marketing-solutions/vigenair/assets/89521555/79dd0b36-0e6e-4103-8ccc-488cd2ec7511)

**Comment by mohabfekry** [comment]
Thanks for opening the issue. 

For the issue you raised in the first comment, I am unable to reproduce it. Are you sure you are on the latest version of the app? We had an issue with clasp which was solved with this commit: https://github.com/google-marketing-solutions/vigenair/commit/5b4bbcd1be1a5da9add3a6b58b8f61a8cc47a0ff

For the issue in the second comment, this is expected as the Cloud Function is not an HTTP one, and so will not be accessible via the web. It is a Cloud Storage triggered function.

I would suggest you `git reset --hard` your working directory, pull the latest changes from GitHub, and rerun the `npm start` script. If your Cloud Function has been deployed correctly already there is no need for you to redeploy it; just deploy the UI (which should work with the latest GitHub changes).

**Comment by kng246** [comment]
@mohabfekry  My branch is up to date with the latest commit, but I'm still getting the error

**Comment by mohabfekry** [comment]
@kng246 please globally install clasp first: `npm install @google/clasp -g` before running `npm start`. This should solve it.
